### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by honza**
2022-08-25-155043-screenshot

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Comment by dtantsur** [comment]
wow, thanks! one request: now that bootstrap is not used, could you do something about links? at least remove the difference between visited and unvisited ones since it causes a lot of visual noise.

**Comment by honza** [comment]
> at least remove the difference between visited and unvisited ones

Done

**Comment by honza** [comment]
2022-08-25-162537-screenshot

**Comment by dtantsur** [comment]
At a risk of torturing you with nit picks: could you keep patch links and project links different?

**Comment by honza** [comment]
> could you keep patch links and project links different?

Something like this?

2022-08-25-165231-screenshot

**Comment by dtantsur** [comment]
Yeah, could be indentation, could be a different color (see the current version).

**Pull request merged**
